# Generated by Django 4.2.7 on 2025-08-05 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("infrastructure_database", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("file_size", models.BigIntegerField()),
                ("mime_type", models.CharField(max_length=100)),
                ("file_url", models.URLField(max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("processing", "Processing"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                            ("archived", "Archived"),
                        ],
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                (
                    "receipt_type",
                    models.CharField(
                        choices=[
                            ("purchase", "Purchase"),
                            ("expense", "Expense"),
                            ("invoice", "Invoice"),
                            ("bill", "Bill"),
                            ("other", "Other"),
                        ],
                        default="purchase",
                        max_length=20,
                    ),
                ),
                ("ocr_data", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Receipt",
                "verbose_name_plural": "Receipts",
                "db_table": "receipts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user"], name="receipts_user_id_1887b7_idx"),
                    models.Index(fields=["status"], name="receipts_status_7da223_idx"),
                    models.Index(
                        fields=["receipt_type"], name="receipts_receipt_946689_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="receipts_created_e99baf_idx"
                    ),
                    models.Index(
                        fields=["processed_at"], name="receipts_process_f93a85_idx"
                    ),
                    models.Index(
                        fields=["user", "status"], name="receipts_user_id_254d35_idx"
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="receipts_user_id_f53a59_idx",
                    ),
                ],
            },
        ),
    ]
