# Generated by Django 4.2.7 on 2025-08-13 02:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("infrastructure_database", "0006_transaction_client"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="client",
            new_name="clients_owner_i_2423e9_idx",
            old_name="clients_owner_idx",
        ),
        migrations.RenameIndex(
            model_name="client",
            new_name="clients_name_0bc5f0_idx",
            old_name="clients_name_idx",
        ),
        migrations.RenameIndex(
            model_name="transaction",
            new_name="transaction_client__6ed13a_idx",
            old_name="tx_client_idx",
        ),
    ]
