# Generated by Django 4.2.7 on 2025-08-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "infrastructure_database",
            "0007_rename_clients_owner_idx_clients_owner_i_2423e9_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="subscription_price_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="subscription_status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
