# Generated by Django 4.2.7 on 2025-08-14 00:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("infrastructure_database", "0009_applicationsettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="Folder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "folder_type",
                    models.CharField(
                        choices=[
                            ("system", "System"),
                            ("user", "User"),
                            ("smart", "Smart"),
                        ],
                        default="user",
                        max_length=10,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="infrastructure_database.folder",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="folders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "folders",
                "ordering": ["name", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="FolderReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "folder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="folder_receipts",
                        to="infrastructure_database.folder",
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipt_folders",
                        to="infrastructure_database.receipt",
                    ),
                ),
            ],
            options={
                "db_table": "folder_receipts",
                "indexes": [
                    models.Index(
                        fields=["folder"], name="folder_rece_folder__980099_idx"
                    ),
                    models.Index(
                        fields=["receipt"], name="folder_rece_receipt_d258e0_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="folderreceipt",
            constraint=models.UniqueConstraint(
                fields=("folder", "receipt"), name="uniq_folder_receipt"
            ),
        ),
        migrations.AddIndex(
            model_name="folder",
            index=models.Index(fields=["user"], name="folders_user_id_37a6af_idx"),
        ),
        migrations.AddIndex(
            model_name="folder",
            index=models.Index(fields=["parent"], name="folders_parent__95398b_idx"),
        ),
        migrations.AddIndex(
            model_name="folder",
            index=models.Index(
                fields=["user", "name"], name="folders_user_id_357691_idx"
            ),
        ),
    ]
