# Generated by Django 4.2.7 on 2025-08-15 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("infrastructure_database", "0011_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "stripe_subscription_id",
                    models.CharField(max_length=255, unique=True),
                ),
                ("stripe_customer_id", models.CharField(max_length=255, unique=True)),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("basic", "Basic"),
                            ("premium", "Premium"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="basic",
                        max_length=50,
                    ),
                ),
                ("status", models.CharField(default="active", max_length=20)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "subscriptions",
                "indexes": [
                    models.Index(
                        fields=["user"], name="subscriptio_user_id_aa8bc6_idx"
                    ),
                    models.Index(
                        fields=["stripe_subscription_id"],
                        name="subscriptio_stripe__aa726e_idx",
                    ),
                    models.Index(
                        fields=["status"], name="subscriptio_status_572d44_idx"
                    ),
                ],
            },
        ),
    ]
