# Generated by Django 4.2.7 on 2025-08-15 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("infrastructure_database", "0012_subscription"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "client_users",
            },
        ),
        migrations.AddField(
            model_name="client",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("archived", "Archived"),
                ],
                default="active",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="vat_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(fields=["status"], name="clients_status_98ee60_idx"),
        ),
        migrations.AddField(
            model_name="clientuser",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_users",
                to="infrastructure_database.client",
            ),
        ),
        migrations.AddField(
            model_name="clientuser",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_clients",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="clientuser",
            index=models.Index(
                fields=["client"], name="client_user_client__4336d1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clientuser",
            index=models.Index(fields=["user"], name="client_user_user_id_1eb083_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="clientuser",
            unique_together={("client", "user")},
        ),
    ]
